mqtt:
  host: 192.168.1.202
  port: 1883
  user: test-mqtt
  password: abc

frigate:
  host: 192.168.1.11
  port: 5000
  cameras:
    - camera_phong_khach
    - camera_phong_lam_viec

#double-take:
#  host: 192.168.1.11
#  port: 3000

gesture:
  handsize: 9000
  confidence: 0.75
  topic: gestures
  detect_all_results: true  # Mặc định chỉ xử lý khi có match
  allowed_persons: []  # Danh sách trống sẽ nhận diện tất cả mọi người
